/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { RandomAnswer } from "./RandomAnswer";
export type { RandomNumberConsumerV2 } from "./RandomNumberConsumerV2";
