/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { RandomAnswer__factory } from "./RandomAnswer__factory";
export { RandomNumberConsumerV2__factory } from "./RandomNumberConsumerV2__factory";
